import type { Project, ProjectImage } from "./types";

// Scope and selection are transcribed from the supplied September 3, 2026 brief.
// This date records preparation of the website content, not project completion.
const preparedAt = "2026-09-06T00:00:00.000Z";

// Descriptions follow the eight board selections after visual inspection.
const photoDescriptions: Record<string, string[]> = {
  "chick-fil-a-kingston": [
    "Chick-fil-A restaurant exterior during construction in Kingston",
    "Side exterior of the Kingston restaurant during construction",
    "Restaurant tile and interior surfaces during the buildout",
    "Wood wall framing for the ground-up restaurant construction",
    "Structural roof trusses above the restaurant framing",
    "Interior wood framing and partitions at Chick-fil-A Kingston",
    "Ceiling coordination during the restaurant interior buildout",
    "Unfinished window wall during the Kingston restaurant construction",
  ],
  "lidl-staten-island": [
    "Lidl retail facade in Staten Island",
    "Storefront entrance at Lidl Staten Island",
    "Exterior facade repairs at the Staten Island retail location",
    "Masonry opening during repair work at Lidl Staten Island",
    "Brick repair detail at the retail property",
    "Interior masonry repair at Lidl Staten Island",
    "Concrete basement floor at the Staten Island retail property",
    "Pavement at the entrance to Lidl Staten Island",
  ],
  "raising-canes-forest-hills": [
    "Completed Raising Cane’s storefront in Forest Hills",
    "Raising Cane’s street-facing storefront and facade",
    "Glass restaurant entrance at Raising Cane’s Forest Hills",
    "Exterior facade panel detail at Raising Cane’s",
    "Facade panel installation at the Forest Hills restaurant",
    "Restaurant entry door and storefront finish detail",
    "Dining room context at the Forest Hills storefront project",
    "Order counter context at the Forest Hills storefront project",
  ],
  "harbor-freight-bronx": [
    "Refreshed Harbor Freight building exterior in the Bronx",
    "Angled view of the painted Harbor Freight exterior",
    "Harbor Freight signage and refreshed front facade",
    "Wide view of the completed retail exterior refresh",
    "Repainted staff room at the Bronx retail location",
    "Staff room walls and lockers after interior painting",
    "Refreshed kitchenette wall in the retail staff area",
    "Staff room ceiling and painted interior finishes",
  ],
  "lidl-harlem": [
    "Polished concrete sales-floor aisle at Lidl Harlem",
    "Wide view of the finished concrete supermarket floor",
    "Finished concrete floor along the retail display wall",
    "Concrete floor at the Lidl Harlem entrance",
    "Finished floor in the supermarket service corridor",
    "Polished concrete floor beneath the retail shelving",
    "Polished concrete floor along the refrigerator aisle",
    "Open retail area with finished polished concrete flooring",
  ],
  "upper-west-side-apartment": [
    "Custom wood kitchen cabinetry and sink in an Upper West Side apartment",
    "Kitchen faucet and stone countertop detail",
    "Renovated apartment bathroom with vanity and mirror",
    "Finished tiled shower in the Upper West Side apartment",
    "Custom living-room cabinetry in the renovated apartment",
    "Finished living room with new hardwood flooring",
    "Custom kitchen cabinet drawer detail",
    "Interior door and hardwood floor in the renovated apartment",
  ],
  "plainview-kitchen": [
    "White kitchen cabinetry and custom range hood in Plainview",
    "Kitchen sink and countertop in the renovated Plainview home",
    "Custom cabinetry and island in the open-plan kitchen",
    "Renovated kitchen and adjoining timber stair rail",
    "Timber and metal rail detail beside the renovated kitchen",
    "Dining area adjoining the open-concept Plainview kitchen",
    "Hardwood floor in the renovated first floor",
    "Framing progress during the open-floor-plan renovation",
  ],
  "tribeca-apartment": [
    "Tribeca bathroom vanity with brass sconces",
    "Renovated bathroom and toilet in the Tribeca apartment",
    "Brass-framed shower door in the renovated bathroom",
    "Marble tile shower in the Tribeca apartment",
    "Brass shower fittings against the tiled wall",
    "Brass faucet detail in the renovated bathroom",
    "Refinished hardwood floor in the Tribeca apartment",
    "Painted column and cornice details in the refreshed apartment",
  ],
  "hicksville-basement": [
    "Wide view of the finished basement in Hicksville",
    "Open finished basement living space",
    "Sliding barn door in the renovated basement",
    "Built-in basement cabinets and finished trim",
    "Stair rail in the renovated Hicksville basement",
    "Finished stair detail in the basement renovation",
    "Basement flooring, interior door and trim",
    "Exposed basement ceiling during renovation",
  ],
  "kings-park-exterior": [
    "Renovated front exterior of the Kings Park home",
    "Front facade with new siding, windows and stone finishes",
    "New siding and windows along the side of the home",
    "Side and rear facade of the renovated Kings Park home",
    "Rear sunroom at the Kings Park exterior renovation",
    "Brick chimney and patio at the renovated home",
    "New rear siding on the Kings Park home",
    "Bay window detail at the completed exterior renovation",
  ],
};

function gallery(slug: string, description: string): ProjectImage[] {
  return Array.from({ length: 8 }, (_, index) => ({
    src: `/images/projects/${slug}/${String(index + 1).padStart(2, "0")}.webp`,
    alt: photoDescriptions[slug]?.[index] ?? description,
  }));
}

export const seedProjects: Project[] = [
  {
    id: "8310b735-2c9a-51e9-b450-14c0ddefaba5",
    slug: "chick-fil-a-kingston",
    title: "Chick-fil-A - Ground-Up Carpentry and Interior Buildout",
    subtitle: "",
    division: "commercial",
    location: "Kingston, New York",
    category: "GROUND-UP COMMERCIAL CONSTRUCTION",
    description:
      "Reliant Renovations completed the comprehensive carpentry and interior-finish package for the ground-up construction of a new restaurant, carrying its scope from initial wood framing through completed interior finishes.",
    result: "",
    scope: [
      "Complete wood stick framing",
      "Installation of structural roof trusses and roof framing",
      "Framing of all interior partitions and soffits",
      "Drywall installation, taping, spackling and finishing",
      "Interior painting",
      "Suspended ceiling-grid installation",
      "Wall wainscoting and stainless-steel trim",
      "Interior door installation",
      "Coordination with the project team and other trades",
    ],
    images: gallery(
      "chick-fil-a-kingston",
      "Chick-fil-A carpentry and interior buildout in Kingston",
    ),
    featured: true,
    published: true,
    order: 0,
    updatedAt: preparedAt,
  },
  {
    id: "a24a0fde-1f30-5ebd-ad72-ea8305fd5026",
    slug: "lidl-staten-island",
    title: "Lidl Staten Island - Masonry and Exterior Restoration",
    subtitle: "",
    division: "commercial",
    location: "Staten Island, New York",
    category: "COMMERCIAL RETAIL RENOVATION",
    description:
      "Reliant Renovations completed masonry, exterior EIFS repair and concrete-floor finishing work at an existing retail location, including extensive interior and exterior repairs.",
    result: "",
    scope: [
      "Project masonry scope",
      "Exterior EIFS facade repairs and restoration",
      "Numerous interior masonry repairs",
      "Masonry work and repairs within the elevator shaft",
      "Grinding and sealing of basement and cellar concrete floors",
      "Coordination of multiple interior and exterior scopes",
    ],
    images: gallery(
      "lidl-staten-island",
      "Lidl masonry and exterior restoration in Staten Island",
    ),
    featured: false,
    published: true,
    order: 1,
    updatedAt: preparedAt,
  },
  {
    id: "25fc77f4-6772-5b6d-bf4b-e12c456168ca",
    slug: "raising-canes-forest-hills",
    title: "Raising Cane's - Storefront and Exterior Facade",
    subtitle: "",
    division: "commercial",
    location: "Forest Hills, New York",
    category: "COMMERCIAL RESTAURANT RENOVATION",
    description:
      "Reliant Renovations completed the glass storefront and exterior facade package for an urban Raising Cane's restaurant location.",
    result: "",
    scope: [
      "Glass storefront installation",
      "Exterior metal-panel installation",
      "ACM composite-panel facade installation",
      "Field coordination of storefront and facade transitions",
      "Associated exterior trim and finish work",
    ],
    images: gallery(
      "raising-canes-forest-hills",
      "Raising Cane’s storefront and facade in Forest Hills",
    ),
    featured: true,
    published: true,
    order: 2,
    updatedAt: preparedAt,
  },
  {
    id: "9a81aae2-1785-5014-a55a-9a171059b133",
    slug: "harbor-freight-bronx",
    title: "Harbor Freight - Interior and Exterior Retail Refresh",
    subtitle: "",
    division: "commercial",
    location: "Bronx, New York",
    category: "COMMERCIAL RETAIL RENOVATION",
    description:
      "Reliant Renovations completed a comprehensive interior and exterior refresh of an operating retail location. The work was phased and performed during off-hours to minimize disruption to store operations.",
    result: "",
    scope: [
      "Repainting of the entire retail interior",
      "Construction of new interior partitions",
      "Removal of designated exterior doors and infill with concrete masonry units",
      "Preparation and repainting of the entire building exterior",
      "Installation of new exterior bollards",
      "Associated patching, preparation and finish work",
      "Off-hours coordination around active store operations",
    ],
    images: gallery(
      "harbor-freight-bronx",
      "Harbor Freight interior and exterior refresh in the Bronx",
    ),
    featured: false,
    published: true,
    order: 3,
    updatedAt: preparedAt,
  },
  {
    id: "4f391daf-b4ff-566e-92f7-894b74f232ee",
    slug: "lidl-harlem",
    title: "Lidl Harlem - Flooring and Selective Demolition",
    subtitle: "",
    division: "commercial",
    location: "Harlem, New York",
    category: "COMMERCIAL RETAIL RENOVATION",
    description:
      "Reliant Renovations completed a multi-phase demolition and polished-concrete flooring package within an existing supermarket. All work was performed during off-hours to accommodate store operations.",
    result: "",
    scope: [
      "Demolition and removal of existing first-floor flooring",
      "Demolition and removal of existing cellar-level flooring",
      "Selective demolition of interior partitions",
      "Preparation of exposed concrete surfaces",
      "Polished concrete flooring throughout the first floor and cellar",
      "Off-hours coordination to minimize operational disruption",
    ],
    images: gallery(
      "lidl-harlem",
      "Lidl polished concrete flooring and renovation in Harlem",
    ),
    featured: false,
    published: true,
    order: 4,
    updatedAt: preparedAt,
  },
  {
    id: "d79a6ca3-1520-5a57-b46e-cec273f5a9e9",
    slug: "upper-west-side-apartment",
    title: "Upper West Side Full Apartment Renovation",
    subtitle: "",
    division: "residential",
    location: "Upper West Side, New York",
    category: "RESIDENTIAL - FULL APARTMENT RENOVATION",
    description:
      "Reliant Renovations completed a full apartment renovation incorporating a custom millwork kitchen, bathroom renovation, new hardwood floors, custom doors and comprehensive finish work.",
    result: "",
    scope: [
      "Complete apartment renovation",
      "Custom millwork kitchen and cabinetry",
      "Bathroom renovation",
      "Installation of new hardwood flooring",
      "Custom interior doors and millwork details",
      "Complete apartment painting and finish work",
      "Coordination of all required trades",
    ],
    images: gallery(
      "upper-west-side-apartment",
      "Full apartment renovation on the Upper West Side",
    ),
    featured: true,
    published: true,
    order: 5,
    updatedAt: preparedAt,
  },
  {
    id: "7b804f3f-f072-5c4a-aed4-fcf39570abff",
    slug: "plainview-kitchen",
    title: "Plainview Kitchen and Open-Concept Renovation",
    subtitle: "",
    division: "residential",
    location: "Plainview, New York",
    category: "RESIDENTIAL - KITCHEN AND FIRST-FLOOR RENOVATION",
    description:
      "Reliant Renovations completed a comprehensive kitchen and first-floor renovation designed to create a more open and functional living environment.",
    result: "",
    scope: [
      "Removal of walls and installation of a structural steel header to open the floor plan",
      "Relocation of plumbing for the new kitchen layout",
      "Supply and installation of custom kitchen cabinetry",
      "Fabrication and installation of a custom range hood",
      "Custom island accent feature",
      "New hardwood flooring in the kitchen",
      "Refinishing of existing hardwood flooring throughout adjoining areas",
      "Repainting of the entire first floor",
      "Complete kitchen renovation from demolition through final finishes",
    ],
    images: gallery(
      "plainview-kitchen",
      "Custom kitchen and open-concept renovation in Plainview",
    ),
    featured: true,
    published: true,
    order: 6,
    updatedAt: preparedAt,
  },
  {
    id: "4dce6d00-bab2-5b3d-a81f-a05c224b6ce6",
    slug: "tribeca-apartment",
    title: "Tribeca Apartment and Bathroom Renovation",
    subtitle: "",
    division: "residential",
    location: "Tribeca, New York",
    category: "RESIDENTIAL - APARTMENT RENOVATION",
    description:
      "Reliant Renovations renovated two bathrooms and refreshed the full apartment through comprehensive painting and hardwood-floor refinishing.",
    result: "",
    scope: [
      "Complete renovation of two bathrooms",
      "New bathroom tile, fixtures and finish work",
      "Preparation and repainting throughout the apartment",
      "Refinishing of existing hardwood flooring",
      "Associated carpentry, patching and trade coordination",
    ],
    images: gallery(
      "tribeca-apartment",
      "Apartment and bathroom renovation in Tribeca",
    ),
    featured: false,
    published: true,
    order: 7,
    updatedAt: preparedAt,
  },
  {
    id: "38e6f59f-d3df-52c2-bc8a-9625a16b3960",
    slug: "hicksville-basement",
    title: "Hicksville Full Basement Renovation",
    subtitle: "",
    division: "residential",
    location: "Hicksville, New York",
    category: "RESIDENTIAL - BASEMENT RENOVATION",
    description:
      "Reliant Renovations transformed the existing basement into a completely finished living space, managing the project from its original condition through final completion.",
    result: "",
    scope: [
      "Complete basement renovation from demolition through finishes",
      "New interior framing and layout",
      "Finished walls and ceilings",
      "Electrical and lighting improvements",
      "Interior doors, trim and finish carpentry",
      "Flooring installation",
      "Complete painting and finish work",
      "Coordination of all required trades",
    ],
    images: gallery(
      "hicksville-basement",
      "Full basement renovation in Hicksville",
    ),
    featured: false,
    published: true,
    order: 8,
    updatedAt: preparedAt,
  },
  {
    id: "e9eea623-a7b2-5ce7-8f44-de1069ea817f",
    slug: "kings-park-exterior",
    title: "Kings Park Exterior Transformation",
    subtitle: "",
    division: "residential",
    location: "Kings Park, New York",
    category: "RESIDENTIAL - EXTERIOR RENOVATION",
    description:
      "Reliant Renovations completed a full exterior renovation that modernized the home and improved its building envelope.",
    result: "",
    scope: [
      "Removal of existing siding and windows",
      "Supply and installation of new exterior siding",
      "Supply and installation of new windows throughout the home",
      "Installation of new exterior stone finishes",
      "Interior patching, preparation and painting around replaced windows",
      "Associated exterior trim and finish work",
    ],
    images: gallery(
      "kings-park-exterior",
      "Siding, windows and exterior stone renovation in Kings Park",
    ),
    featured: false,
    published: true,
    order: 9,
    updatedAt: preparedAt,
  },
];
